version: '3.9'

services:
  best-movies-web:
    build:
      context: ./best-movies-web
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - best-movies-api
  
  best-movies-api:
    build: 
      context: ./BestMovies.Net
      dockerfile: ./BestMovies.Api/Dockerfile
    ports:
      - 4500:80
    environment:
      - ASPNETCORE_ENV=Development