version: '3.9'

services:
  #best-movies-proxy:
  #  build:
  #    context: ./best-movies-proxy
  #    dockerfile: Dockerfile
  #  image: antonjanto/best-movies-proxy
  #  container_name: best-movies-proxy
  #  ports:
  #    - 80:80

  best-movies-web:
    build:
      context: ./best-movies-web
      dockerfile: Dockerfile
    image: antonjanto/best-movies-web
    container_name: best-movies-web
    ports:
      - 80:80
    links:
      - "best-movies-api:api"
    #depends_on:
    #  - best-movies-proxy
  
  best-movies-api:
    build: 
      context: ./BestMovies.Net
      dockerfile: ./BestMovies.Api/Dockerfile
    image: antonjanto/best-movies-api
    container_name: best-movies-api
    ports:
      - 5000:80
    #depends_on:
    #  - best-movies-proxy