version: '3.9'

services:
  best-movies-web:
    build:
      context: ./best-movies-web
      dockerfile: Dockerfile
    image: antonjanto/best-movies-web
    ports:
      - 8080:80
    depends_on:
      - best-movies-api
  
  best-movies-api:
    build: 
      context: ./BestMovies.Net
      dockerfile: ./BestMovies.Api/Dockerfile
    image: antonjanto/best-movies-api
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000