name: Dockerize BestMovies Inc.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker-Hub Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN
        
    - name: Docker Compose Build
      run: docker-compose build
        
    - name: Docker Compose push to Docker Hub
      run: docker-compose push
      
    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
        application_name: BestMovies-SEP6
        environment_name: best-movies-env
        version_label: bestmovies-1.0.0
