name: Dockerize BestMovies Inc.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker-Hub Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN
        
    - name: Docker Compose Build
      run: docker-compose build
        
    - name: Docker Compose push to Docker Hub
      run: docker-compose push
